language: cpp

notifications: 
  email: false

git:
  submodules: false
  depth: 1

services: 
  - docker

dist: trusty
sudo: required

matrix:
  include:
  - os: linux
    env:
      - PLATFORM="ubuntu-18.04"
  - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    git clone https://github.com/skymizer/SkyPat.git &&
    cd SkyPat && 
    ./autogen.sh &&
    ./configure &&
    make install ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo docker pull luishsu/wvmcc:${PLATFORM} &&
    sudo docker create --privileged=true -t --name ${PLATFORM} --volume ${TRAVIS_BUILD_DIR}:/root luishsu/wvmcc:${PLATFORM} &&
    sudo docker start ${PLATFORM} ;
    fi

script: 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo docker exec -t ${PLATFORM} /bin/bash -c "mkdir ~/build-cmake" &&
    sudo docker exec -t ${PLATFORM} /bin/bash -c "cd ~/build-cmake && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install-cmake .." &&
    sudo docker exec -t ${PLATFORM} /bin/bash -c "cd ~/build-cmake && make -j8 install" &&
    sudo docker exec -t ${PLATFORM} /bin/bash -c "cd ~/build-cmake && ctest" ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    mkdir ${TRAVIS_BUILD_DIR}/build-cmake &&
    cd ${TRAVIS_BUILD_DIR}/build-cmake &&
    cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/install-cmake .. &&
    make -j8 install &&
    ctest ;
    fi
  
