version: 2.0
jobs:
  "unit-test":
    docker:
      - image: ubuntu:latest
    steps:
      - run:
          name: "Install prerequisite"
          command:
            apt-get update && apt-get install -y git ssh tar gzip ca-certificates cmake wget automake autoconf libtool build-essential
      - checkout
      - restore_cache:
          keys:
            - SkyPat-install
      - run:
          name: "Build SkyPat"
          command:
            "if [ ! -d SkyPat-install ]; then mkdir -p SkyPat-install && export SKYPAT_PATH=$PWD/SkyPat-install && git clone --branch v3.1.1 --depth 1 https://github.com/skymizer/SkyPat.git SkyPat-src && cd SkyPat-src && ./autogen.sh && ./configure --prefix=$SKYPAT_PATH && make install && cd .. ; fi"
      - save_cache:
          key: SkyPat-install
          paths:
            - "SkyPat-install"
      - run:
          name: "Build"
          command: 
            mkdir -p build &&
            cd build &&
            cmake -DCMAKE_BUILD_TYPE=Debug -DSKYPAT_INCLUDE_DIR=../SkyPat-install/include -DSKYPAT_LIBRARY_DIR=../SkyPat-install/lib ..
      - run:
          name: "Test"
          command: 
            cd build && ctest
  
workflows:
  version: 2
  commit:
    jobs:
      - "unit-test"