version: 2.0
jobs:
  "unit-test":
    docker:
      - image: ubuntu:latest
    steps:
      - run:
          name: "Install CircleCI prerequisite"
          command:
            apt-get update && apt-get install -y git ssh tar gzip ca-certificates
      - checkout
      - run:
          name: "Build"
          command: 
            mkdir -p build &&
            cd build &&
            cmake -DCMAKE_BUILD_TYPE=Debug ..
      - run:
          name: "Test"
          command: 
            ctest
  
workflows:
  version: 2
  commit:
    jobs:
      - "unit-test"